#!/usr/bin/env python3
r"""Render a ``/research-gather`` ``bib_ledger.yml`` into ``guide/references.bib``.

Input contract = the research-gather bibliography schema (see
``research_toolkit/validators/bib_ledger.py``): a top-level ``entries:`` list of
mappings with required ``{bibkey, primary_url, title, status, claim_family}`` and
optional ``{authors, venue, code_url, published_online}``.

This is deliberately **not** the bespoke hand-curated "debate ledger"
(``sources:`` with ``{tier, debate, role}``, no title/url) that a few gold guides
ship — those have no machine-reconstructable bibliography and keep their
hand-written ``.bib``. This converter:
  * refuses a ledger lacking ``entries:`` (so it never touches debate ledgers), and
  * refuses to overwrite a ``references.bib`` that lacks the GENERATED sentinel
    unless ``--force`` (so it never clobbers a hand-authored bib).

Output is bibkey-sorted with a sentinel header → byte-stable / idempotent.

Usage (from host repo root)::

    python -m tooling.generate.bib_ledger_to_bib <topic>/<slug>     # one guide (dir or slug)
    python -m tooling.generate.bib_ledger_to_bib --all             # every guide with a ledger
    python -m tooling.generate.bib_ledger_to_bib <slug> --force     # overwrite a hand-authored bib
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

import yaml

from tooling import discovery

SENTINEL = (
    "% GENERATED by tooling.generate.bib_ledger_to_bib from "
    "review/research/bib_ledger.yml — edit the ledger, not this file."
)

_CONF_HINTS = (
    "neurips", "nips", "icml", "iclr", "kdd", "cvpr", "acl", "emnlp", "naacl",
    "aaai", "ijcai", "sigir", "www ", "vldb", "sigmod", "interspeech", "colt",
    "uai", "aistats", "recsys", "wsdm", "coling", "eccv", "iccv", "mlsys",
)
_JOURNAL_HINTS = ("journal", "transactions", "jmlr", "tmlr", "proceedings of the", " vol", "review of", "quarterly")


def _year(*texts: str) -> str | None:
    for t in texts:
        m = re.search(r"\b(19|20)\d{2}\b", t or "")
        if m:
            return m.group(0)
    return None


def _arxiv_id(url: str) -> str | None:
    m = re.search(r"arxiv\.org/abs/(\d{4}\.\d{4,5}(?:v\d+)?)", url or "")
    return m.group(1) if m else None


def _escape_amp(s: str) -> str:
    r"""Escape a bare ``&`` (not already ``\&``) — the unambiguous LaTeX
    alignment-tab breaker. Math-safe (touches nothing else), idempotent."""
    return re.sub(r"(?<!\\)&", r"\\&", s)


# Math spans are passed through verbatim so e.g. a title "$x_i$" keeps its
# subscript while a literal "SHUFFLE_HASH" gets its underscore escaped. The
# delimiter forms (\(..\) / \[..\]) use .*? to the REAL closing token (NOT
# [^)]/[^]], which break on an internal ) or ]). The $-span's opening $ carries a
# (?<!\\) guard so an already-escaped \$ (a literal dollar) is never read as a
# math delimiter.
_MATH_SPAN_RE = re.compile(r"(?<!\\)\$[^$]*\$|\\\(.*?\\\)|\\\[.*?\\\]", re.DOTALL)
# A literal dollar is virtually always a price ($5, $10) — escape a $ that is
# followed by a digit (and not already escaped) BEFORE math-span detection, so it
# can never form a spurious $...$ pair with real math elsewhere.
_PRICE_DOLLAR_RE = re.compile(r"(?<!\\)\$(?=\d)")
_SPECIALS = ("&", "%", "#", "_")


def _escape_specials(s: str) -> str:
    r"""Idempotently escape each of ``& % # _`` (``(?<!\\)`` guard → no double-escape)."""
    for ch in _SPECIALS:
        s = re.sub(r"(?<!\\)" + re.escape(ch), "\\" + ch, s)
    return s


def _escape_text(s: str) -> str:
    r"""Escape LaTeX specials in a free-text field (``title`` / ``venue`` /
    ``note``) OUTSIDE math. Idempotent on already-escaped input. URLs are
    ``\url{}``-wrapped at the call site so their underscores never reach here.
    A literal price ``$N`` is escaped; a balanced ``$...$`` math span (e.g.
    ``$x_i$``) is preserved — even when a literal price sits beside it, because
    the price ``$`` is escaped first. ``$`` / ``^`` / ``~`` inside math are kept."""
    s = _PRICE_DOLLAR_RE.sub(r"\\$", s)  # prices first → no spurious math pairing
    out, last = [], 0
    for m in _MATH_SPAN_RE.finditer(s):
        out.append(_escape_specials(s[last:m.start()]))
        out.append(m.group(0))  # math span verbatim
        last = m.end()
    out.append(_escape_specials(s[last:]))
    return "".join(out)


def _entry_type(e: dict) -> str:
    url = (e.get("primary_url") or "").lower()
    venue = (e.get("venue") or "").lower()
    if "arxiv.org" in url or "arxiv" in venue or "preprint" in venue:
        return "article"
    if any(h in venue for h in _CONF_HINTS):
        return "inproceedings"
    if any(h in venue for h in _JOURNAL_HINTS):
        return "article"
    if any(k in url for k in ("blog", "medium.", "substack", ".io/", "/blog")) or "blog" in venue or "essay" in venue:
        return "online"
    return "misc"


def _authors(a: str | None) -> str | None:
    if not a:
        return None
    a = re.sub(r"\s*\((?:19|20)\d{2}\)\s*$", "", a.strip()).strip()  # drop trailing "(2021)"
    a = a.replace(" & ", " and ")  # biblatex needs ' and ' between authors; raw & = align tab
    et_al = bool(re.search(r"\bet\s+al\.?$", a, re.IGNORECASE))
    if et_al:
        a = re.sub(r"\s*,?\s*et\s+al\.?$", "", a, flags=re.IGNORECASE).strip()
    # A comma-separated list of FULL "First Last" names is what biber rejects as
    # "too many commas". Split on commas ONLY when EVERY comma token is multi-word
    # — so a single "Last, First" and a "Last, Suffix, First" / "von Last, Jr,
    # First" name are preserved (their tokens include single words), while a real
    # "First Last, First Last[, ...]" list (every token a 2+-word name) is joined
    # with ' and '. An ambiguous "Last, First, Last, First" list is left for the
    # author to disambiguate rather than silently shredded into phantom authors.
    if " and " not in a and "," in a:
        toks = [t.strip() for t in a.split(",") if t.strip()]
        # Split only when every token is a multi-word "First Last" name AND the
        # first token does not start with a lowercase surname particle (van/von/de
        # ...). The particle guard preserves a single "van der Berg, Johann Smith"
        # (Last, First) rather than shredding it into two phantom authors.
        if (len(toks) >= 2 and all(" " in t for t in toks)
                and not (toks[0][:1].islower())):
            a = " and ".join(toks)
    if et_al:
        a = (a + " and others") if a else "others"
    return _escape_amp(a)  # backstop for any remaining bare & (e.g. "AT&T")


def render_entry(e: dict) -> str:
    btype = _entry_type(e)
    venue = (e.get("venue") or "").strip()
    axid = _arxiv_id(e.get("primary_url", ""))
    fields: list[tuple[str, str]] = []

    au = _authors(e.get("authors"))
    if au:
        fields.append(("author", au))
    if e.get("title"):
        # extra braces protect case; _escape_text escapes & _ # % outside math
        fields.append(("title", "{" + _escape_text(e["title"].strip()) + "}"))
    if btype == "inproceedings" and venue:
        fields.append(("booktitle", _escape_text(venue)))
    elif btype == "article" and venue and not axid:
        fields.append(("journal", _escape_text(venue)))
    # An explicit ledger ``year:`` wins; otherwise derive from venue /
    # published_online. The derivation regex can mis-fire on an arXiv id that
    # leads with a 19xx/20xx-looking prefix (e.g. arXiv:1907.07271 → "1907"),
    # so the explicit field is the documented override for those cases.
    yr = str(e["year"]) if e.get("year") is not None else _year(
        venue, str(e.get("published_online") or "")
    )
    if yr:
        fields.append(("year", yr))
    if e.get("primary_url"):
        fields.append(("url", e["primary_url"].strip()))
    notes: list[str] = []
    if axid:
        notes.append(f"arXiv:{axid}")
    if venue and btype == "misc":
        notes.append(_escape_text(venue))
    if e.get("code_url"):
        # \url{} renders the URL safely (underscores etc. need no escaping inside it)
        notes.append("code: \\url{" + e["code_url"].strip() + "}")
    if notes:
        fields.append(("note", "; ".join(notes)))

    body = "\n".join(f"  {k} = {{{v}}}," for k, v in fields)
    return f"@{btype}{{{e['bibkey']},\n{body}\n}}"


def render_bib(entries: list[dict]) -> str:
    entries = sorted(entries, key=lambda e: str(e.get("bibkey", "")))
    out = [SENTINEL, f"% {len(entries)} entries · regenerate: python -m tooling.generate.bib_ledger_to_bib <guide>", ""]
    for e in entries:
        out.append(render_entry(e))
        out.append("")
    return "\n".join(out)


# A regenerated bib is the ledger's. But guides routinely hand-append extra
# ``@entry`` blocks below it (e.g. the Gold appendix-E/F citation sources that
# are NOT in the research-gather ledger). Overwriting blindly would silently
# delete those and turn every E/F \parencite into an undefined-citation build
# error. So preserve any entry whose bibkey is not in the ledger, below a marker.
MANUAL_DIVIDER = (
    "% --- manual entries below (bibkeys not in bib_ledger.yml) are PRESERVED "
    "across regeneration; move them into the ledger to have them managed ---"
)
_ENTRY_START_RE = re.compile(r"@\w+\{([^,\n]+),")


def _entry_blocks(text: str) -> list[tuple[str, str]]:
    """(bibkey, full ``@entry`` block) for each entry in a .bib, in file order.

    Brace-aware: walks from each ``@type{key,`` to its matching close brace so a
    multi-line braced field (e.g. a long abstract with ``}`` on its own line) or
    an indented final ``}`` does not truncate / drop the entry — the regex form
    ``.*?^\\}$`` did both, silently losing hand-appended manual entries."""
    out: list[tuple[str, str]] = []
    pos = 0
    while True:
        m = _ENTRY_START_RE.search(text, pos)
        if not m:
            return out
        start = m.start()
        # Skip a commented-out entry (an unescaped % before the @ on its line) so a
        # `% @misc{old,...}` is never resurrected as a live orphan on regeneration.
        line_start = text.rfind("\n", 0, start) + 1
        if re.search(r"(?<!\\)%", text[line_start:start]):
            pos = m.end()
            continue
        # Cap the brace walk at the NEXT entry start: an unbalanced/malformed entry
        # then stops there instead of swallowing every following entry.
        nxt = _ENTRY_START_RE.search(text, m.end())
        limit = nxt.start() if nxt else len(text)
        depth, j = 0, text.index("{", start)  # the '{' right after @type
        while j < limit:
            c = text[j]
            if c == "{":
                depth += 1
            elif c == "}":
                depth -= 1
                if depth == 0:
                    j += 1
                    break
            j += 1
        end = j if depth == 0 else limit
        out.append((m.group(1).strip(), text[start:end].rstrip()))
        pos = max(end, m.end())


def convert(guide_dir: Path, force: bool = False) -> str:
    ledger = guide_dir / "review" / "research" / "bib_ledger.yml"
    bib = guide_dir / "guide" / "references.bib"
    data = yaml.safe_load(ledger.read_text(encoding="utf-8")) or {}
    entries = data.get("entries")
    if not entries:
        raise ValueError(
            f"{ledger}: no 'entries:' list (research-gather schema required; "
            f"hand-curated 'sources:' debate ledgers are not convertible)"
        )
    ledger_keys = {str(e.get("bibkey", "")).strip() for e in entries}
    orphans: list[str] = []
    if bib.exists():
        existing = bib.read_text(encoding="utf-8")
        has_real_entries = bool(re.search(r"(?m)^@\w+\{", existing))
        # Freely overwrite a stub (no @ entries) or a previously-GENERATED file;
        # only a hand-authored bib WITH real entries needs --force.
        if has_real_entries and SENTINEL not in existing[:300] and not force:
            raise ValueError(
                f"{bib} is hand-authored (has @ entries, no GENERATED sentinel); "
                f"rerun with --force to overwrite"
            )
        orphans = [block for key, block in _entry_blocks(existing) if key not in ledger_keys]
    rendered = render_bib(entries)  # ends "...lastentry\n"
    if orphans:
        text = (rendered.rstrip("\n") + "\n\n" + MANUAL_DIVIDER + "\n\n"
                + "\n\n".join(orphans) + "\n")
    else:
        text = rendered + "\n"  # preserve the original "...lastentry\n\n" trailing
    bib.parent.mkdir(parents=True, exist_ok=True)
    bib.write_text(text, encoding="utf-8")
    return str(bib)


def _resolve(arg: str) -> Path:
    p = Path(arg)
    if (p / "guide_qa.yaml").exists():
        return p
    for gd in discovery.iter_guide_dirs():
        if gd.name == arg:
            return gd
    raise SystemExit(f"no guide matching {arg!r}")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("guide", nargs="?", help="guide dir or slug")
    ap.add_argument("--all", action="store_true", help="every guide that has a bib_ledger.yml")
    ap.add_argument("--force", action="store_true", help="overwrite a hand-authored references.bib")
    args = ap.parse_args()

    if args.all:
        targets = [g for g in discovery.iter_guide_dirs() if (g / "review/research/bib_ledger.yml").exists()]
    elif args.guide:
        targets = [_resolve(args.guide)]
    else:
        ap.error("specify a guide or --all")

    n = 0
    for gd in targets:
        try:
            path = convert(gd, force=args.force)
            print(f"  WROTE  {path}")
            n += 1
        except ValueError as e:
            print(f"  SKIP   {e}")
    print(f"\n{n} references.bib written.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
