#!/usr/bin/env python3
r"""Render a ``/research-gather`` ``bib_ledger.yml`` into ``guide/references.bib``.

Input contract = the research-gather bibliography schema (see
``research_toolkit/validators/bib_ledger.py``): a top-level ``entries:`` list of
mappings with required ``{bibkey, primary_url, title, status, claim_family}`` and
optional ``{authors, venue, code_url, published_online}``.

This is deliberately **not** the bespoke hand-curated "debate ledger"
(``sources:`` with ``{tier, debate, role}``, no title/url) that a few gold guides
ship — those have no machine-reconstructable bibliography and keep their
hand-written ``.bib``. This converter:
  * refuses a ledger lacking ``entries:`` (so it never touches debate ledgers), and
  * refuses to overwrite a ``references.bib`` that lacks the GENERATED sentinel
    unless ``--force`` (so it never clobbers a hand-authored bib).

Output is bibkey-sorted with a sentinel header → byte-stable / idempotent.

Usage (from host repo root)::

    python -m tooling.generate.bib_ledger_to_bib <topic>/<slug>     # one guide (dir or slug)
    python -m tooling.generate.bib_ledger_to_bib --all             # every guide with a ledger
    python -m tooling.generate.bib_ledger_to_bib <slug> --force     # overwrite a hand-authored bib
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

import yaml

from tooling import discovery

SENTINEL = (
    "% GENERATED by tooling.generate.bib_ledger_to_bib from "
    "review/research/bib_ledger.yml — edit the ledger, not this file."
)

_CONF_HINTS = (
    "neurips", "nips", "icml", "iclr", "kdd", "cvpr", "acl", "emnlp", "naacl",
    "aaai", "ijcai", "sigir", "www ", "vldb", "sigmod", "interspeech", "colt",
    "uai", "aistats", "recsys", "wsdm", "coling", "eccv", "iccv", "mlsys",
)
_JOURNAL_HINTS = ("journal", "transactions", "jmlr", "tmlr", "proceedings of the", " vol", "review of", "quarterly")


def _year(*texts: str) -> str | None:
    for t in texts:
        m = re.search(r"\b(19|20)\d{2}\b", t or "")
        if m:
            return m.group(0)
    return None


def _arxiv_id(url: str) -> str | None:
    m = re.search(r"arxiv\.org/abs/(\d{4}\.\d{4,5}(?:v\d+)?)", url or "")
    return m.group(1) if m else None


def _entry_type(e: dict) -> str:
    url = (e.get("primary_url") or "").lower()
    venue = (e.get("venue") or "").lower()
    if "arxiv.org" in url or "arxiv" in venue or "preprint" in venue:
        return "article"
    if any(h in venue for h in _CONF_HINTS):
        return "inproceedings"
    if any(h in venue for h in _JOURNAL_HINTS):
        return "article"
    if any(k in url for k in ("blog", "medium.", "substack", ".io/", "/blog")) or "blog" in venue or "essay" in venue:
        return "online"
    return "misc"


def _authors(a: str | None) -> str | None:
    if not a:
        return None
    a = re.sub(r"\s*\((?:19|20)\d{2}\)\s*$", "", a.strip()).strip()  # drop trailing "(2021)"
    if re.search(r"\bet\s+al\.?$", a, re.IGNORECASE):
        first = re.sub(r"\s*,?\s*et\s+al\.?$", "", a, flags=re.IGNORECASE).strip()
        return f"{first} and others"
    return a


def render_entry(e: dict) -> str:
    btype = _entry_type(e)
    venue = (e.get("venue") or "").strip()
    axid = _arxiv_id(e.get("primary_url", ""))
    fields: list[tuple[str, str]] = []

    au = _authors(e.get("authors"))
    if au:
        fields.append(("author", au))
    if e.get("title"):
        fields.append(("title", "{" + e["title"].strip() + "}"))  # extra braces protect case
    if btype == "inproceedings" and venue:
        fields.append(("booktitle", venue))
    elif btype == "article" and venue and not axid:
        fields.append(("journal", venue))
    yr = _year(venue, str(e.get("published_online") or ""))
    if yr:
        fields.append(("year", yr))
    if e.get("primary_url"):
        fields.append(("url", e["primary_url"].strip()))
    notes: list[str] = []
    if axid:
        notes.append(f"arXiv:{axid}")
    if venue and btype == "misc":
        notes.append(venue)
    if e.get("code_url"):
        notes.append("code: " + e["code_url"].strip())
    if notes:
        fields.append(("note", "; ".join(notes)))

    body = "\n".join(f"  {k} = {{{v}}}," for k, v in fields)
    return f"@{btype}{{{e['bibkey']},\n{body}\n}}"


def render_bib(entries: list[dict]) -> str:
    entries = sorted(entries, key=lambda e: str(e.get("bibkey", "")))
    out = [SENTINEL, f"% {len(entries)} entries · regenerate: python -m tooling.generate.bib_ledger_to_bib <guide>", ""]
    for e in entries:
        out.append(render_entry(e))
        out.append("")
    return "\n".join(out)


def convert(guide_dir: Path, force: bool = False) -> str:
    ledger = guide_dir / "review" / "research" / "bib_ledger.yml"
    bib = guide_dir / "guide" / "references.bib"
    data = yaml.safe_load(ledger.read_text(encoding="utf-8")) or {}
    entries = data.get("entries")
    if not entries:
        raise ValueError(
            f"{ledger}: no 'entries:' list (research-gather schema required; "
            f"hand-curated 'sources:' debate ledgers are not convertible)"
        )
    if bib.exists():
        head = bib.read_text(encoding="utf-8")[:300]
        if SENTINEL not in head and not force:
            raise ValueError(
                f"{bib} is hand-authored (no GENERATED sentinel); rerun with --force to overwrite"
            )
    bib.parent.mkdir(parents=True, exist_ok=True)
    bib.write_text(render_bib(entries) + "\n", encoding="utf-8")
    return str(bib)


def _resolve(arg: str) -> Path:
    p = Path(arg)
    if (p / "guide_qa.yaml").exists():
        return p
    for gd in discovery.iter_guide_dirs():
        if gd.name == arg:
            return gd
    raise SystemExit(f"no guide matching {arg!r}")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("guide", nargs="?", help="guide dir or slug")
    ap.add_argument("--all", action="store_true", help="every guide that has a bib_ledger.yml")
    ap.add_argument("--force", action="store_true", help="overwrite a hand-authored references.bib")
    args = ap.parse_args()

    if args.all:
        targets = [g for g in discovery.iter_guide_dirs() if (g / "review/research/bib_ledger.yml").exists()]
    elif args.guide:
        targets = [_resolve(args.guide)]
    else:
        ap.error("specify a guide or --all")

    n = 0
    for gd in targets:
        try:
            path = convert(gd, force=args.force)
            print(f"  WROTE  {path}")
            n += 1
        except ValueError as e:
            print(f"  SKIP   {e}")
    print(f"\n{n} references.bib written.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
